### ISSUE TITLE
[Solved/Closed] Mob Spawning Issue in Main World

### ISSUE THREAD

**Issue by pinkpig3777** [DmitryRendov/GriefPreventionFlags#15]
@DmitryRendov There's been an issue on my server for quite a while where players could not find any naturally spawned hostile mobs in the main world ("world") on my server. I have seen naturally spawned hostile mobs in other worlds though and the issue does not effect spawners. Similarly, the flags from this plugin do not effect spawners. So I decided to try removing this plugin. That immediately fixed the issue. 

In other words, this plugin for whatever reason is preventing hostile mobs from spawning in "world" on my server. Not sure if this is a bug or a setting I overlooked. Please help.

**Spigot Version:** CraftBukkit version git-Spigot-642f6d2-57ab4cf (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
**GriefPreventionFlags Version:** v4.5.2
**Plugins (After removing this plugin):** https://gyazo.com/080ea56a1617ab53f65e2ecb6f86251f
**Flags.yml:** https://pastebin.com/caZRmqUr

Thanks!

**Comment by pinkpig3777** [comment]
Actually I'm not sure if this solved the issue after all. I had also changed the difficulty from normal to hard at the same time so that may be why players noticed more mobs. However the issue appears to be still occurring.

**Comment by pinkpig3777** [comment]
So to correct my post, very few mobs were/are spawning in the overworld*. So there were mobs just not many.

**Comment by PiggiesGoSqueal** [comment]
Issue has been solved. It was not caused by this plugin. Changing bukkit.yml mob spawn limit line fixed it.

**Comment by DmitryRendov** [comment]
thank you, closed.
