### ISSUE TITLE
Add Phantom as monster in FlagDef_NoMonsterSpawns.java

### ISSUE THREAD

**Issue by mirolm** [DmitryRendov/GriefPreventionFlags#16]
Please add Phantom in isMonster at line 43 as it is with GHAST, MAGMA_CUBE and SHULKER.

Again PHANTOM is not Monster but Mob. If you set +NoMonsterSpawns phantoms will continue to spawn and kill players, because they are not included in the check.

Spigot git-Spigot-500ff5d-1cead62 (MC: 1.13.1)
GriefPrevention v16.9
GriefPreventionFlags v4.6.1

**Comment by DmitryRendov** [comment]
@mirolm fixed in 78295f212693555463c8f5adfb3e8c8d07d1b4ab, try [4.6.2](https://github.com/DmitryRendov/GriefPreventionFlags/releases/tag/4.6.2)
