### ISSUE TITLE
AllowPvP flags makes dragon fight too easy

### ISSUE THREAD

**Issue by iNko97** [DmitryRendov/GriefPreventionFlags#2]
AreaEffectCloud entities are set to deal no damage, and I would like to rebalance that, but I have not found yet a way to differentiate between players or contraptions throwing lingering potions vs dragon using breath attack
Sketched and not working code should be like this, but...

```
if(damager.getType() == EntityType.AREA_EFFECT_CLOUD)
            if (!(((AreaEffectCloud) damager).getSource() instanceof Player)) return;
```

**Comment by DmitryRendov** [comment]
@iNko97 did you have a chance to find a proper solution? or it's still an issue?
