### ISSUE TITLE
[Solved] NoMonsterSpawns does not remove mobs when they enter a claim.

### ISSUE THREAD

**Issue by pinkpig3777** [DmitryRendov/GriefPreventionFlags#5]
NoMonsterSpawns flag does not remove mobs when they enter a claim like the description says. The creeper walked right into the claim with no issues.

Latest version of plugin is being used.
Spigot Version: This server is running CraftBukkit version git-Spigot-2086bb0-d0a3620 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
Plugins: https://gyazo.com/3250a000be0c566f23defa3175154e10 + Residence (just removed Residence)

Awesome plugin, seriously appreciate you maintaining this. Please fix this bug.

**Comment by iNko97** [comment]
The plugin should remove mobs when they target player in the claim, does this not happen?

**Comment by pinkpig3777** [comment]
@iNko97 It doesn't remove mobs when they target, and even hit, a player in the claim. Just tested it.

**Comment by iNko97** [comment]
Strange. Will test this tomorrow as soon as I am home. Just fyi it won't despawn mobs that were spawned with eggs or mob spawners.

**Comment by iNko97** [comment]
Cannot replicate the bug.
I stand in a claim with noMonsterSpawns flag open, let a naturally spawned mob attack me from outside, as soon as the mobs starts targeting me the mob disappears.

The mobs unfortunately do not despawn when walking around into claims with such flag.

Non-natural monster spawns do not despawn as intended.

Can you please add more details to the bug you are experiencing on your side?

**Comment by pinkpig3777** [comment]
Ah good to know. A player reported the issue which is what I was originally posting about. Then when I said I tested it, I used spawn eggs. Both of your answers have explained the issue. I think the issue has been solved. I'll update this if I discover there are still some issues occurring. 
Thanks!
